"""Add rating_count to Comic (retry)

Revision ID: 51d23007188b
Revises: c2f43df1a0ec
Create Date: 2025-10-17 11:26:22.339085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d23007188b'
down_revision = 'c2f43df1a0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.drop_column('rating_count')

    # ### end Alembic commands ###
