"""Add is_hidden field to Comment model

Revision ID: 6a9ef31bcf54
Revises: eb8e14322f04
Create Date: 2025-10-23 13:50:12.581242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a9ef31bcf54'
down_revision = 'eb8e14322f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.alter_column('chapter_number',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('is_hidden')

    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('chapter_number',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
