"""Add content_type to comics

Revision ID: 95d8febb344c
Revises: 55ad15ab2a3a
Create Date: 2025-10-20 15:53:18.762910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d8febb344c'
down_revision = '55ad15ab2a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
