"""add uploader_id to comic

Revision ID: c2f43df1a0ec
Revises: f793ad4e2228
Create Date: 2025-10-17 10:06:26.551076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f43df1a0ec'
down_revision = 'f793ad4e2228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploader_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['uploader_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('uploader_id')

    # ### end Alembic commands ###
