"""Add content column to chapters

Revision ID: eb8e14322f04
Revises: 95d8febb344c
Create Date: 2025-10-20 16:03:29.655885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb8e14322f04'
down_revision = '95d8febb344c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('chapter_number',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('chapter_number',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
